# Generated by Django 5.1.1 on 2024-09-21 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='opt_out',
            field=models.BooleanField(default=False),
        ),
    ]
