# Generated by Django 5.1.1 on 2024-10-10 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliza', '0002_user_opt_out'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='memory_dict',
        ),
        migrations.AddField(
            model_name='user',
            name='encrypted_memory_dict_string',
            field=models.TextField(null=True),
        ),
    ]
