# Generated by Django 5.1.1 on 2024-10-23 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lliza', '0003_remove_user_memory_dict_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_message_time',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='num_messages',
            field=models.IntegerField(default=0),
        ),
    ]
